services:
  db:
    image: postgres:16
    container_name: minicommerce-postgres
    environment:
      POSTGRES_DB: minicommerce
      POSTGRES_USER: minicommerce
      POSTGRES_PASSWORD: minicommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
