spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minicommerce
    username: minicommerce
    password: minicommerce
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
